encoding: utf-8

# SEO相关信息
title: lexsai
description: lexsai's writeups
keywords: lexsai,CTF,Blog,Web,Security
author: lexsai
footerText: ''

# 这些不要动
permalink: /posts/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

domainUrl: 'https://lexsai.github.io'
baseurl: ''

menu:
  - title: Posts
    url: /
  - title: Categories
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  - title: About
    url: /pages/about.html

extClickEffect: false

extAdsense: false

extMath: false

extCount: false
